from random import randint

import pygame.locals

from crt import Crt
from levels import Bak, ClearKeys, Col, Flash, Game, Shareware

def Title(game: Game, console: Crt):
    ClearKeys(console)
    Col(15, 15, console)
    Bak(0, 0, console)
    console.clrscr()
    console.gotoxy(28, 2)
    console.writeln('Apogee Software Presents')
    ClearKeys(console)
    while not console.keypressed():
        console.gotoxy(1, 5)
        Col(randint(15) + 1, 7, console)
        console.writeln('     ███     ███     ██████████         ███████████        █████████████  (R)')
        console.writeln('     ███▒▒  ███▒▒▒   ███▒▒▒▒▒███▒      ███▒▒▒▒▒▒▒███▒        ▒▒▒▒▒▒████▒▒▒')
        console.writeln('     ███▒▒ ███▒▒▒    ███▒▒   ███▒▒     ███▒▒     ███▒▒            ███▒▒▒▒')
        console.writeln('     ███▒▒███▒▒▒     ███▒▒   ███▒▒    ███▒▒▒      ███▒           ███▒▒▒')
        console.writeln('     ███▒███▒▒▒      ██████████▒▒▒    ███▒▒       ███▒▒         ███▒▒▒')
        console.writeln('     ██████▒▒▒       ███▒▒███▒▒▒▒     ███▒▒       ███▒▒        ███▒▒▒')
        console.writeln('     ███▒███▒        ███▒▒ ███▒        ███▒      ███▒▒▒       ███▒▒▒')
        console.writeln('     ███▒▒███▒       ███▒▒  ███▒       ███▒▒     ███▒▒      ████▒▒▒')
        console.writeln('     ███▒▒ ███▒      ███▒▒   ███▒       ███████████▒▒▒     █████████████')
        console.writeln('     ███▒▒  ███▒       ▒▒▒     ▒▒▒        ▒▒▒▒▒▒▒▒▒▒▒        ▒▒▒▒▒▒▒▒▒▒▒▒▒')
        console.writeln('     ███▒▒   ███▒')
        console.writeln('     ███▒▒    ███████████████████████████████████████████████████████████')
        console.writeln('       ▒▒▒      ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒')
        console.writeln()
        Col(14, 15, console)
        console.gotoxy(11, console.cursor_y)
        console.writeln('DUNGEONS OF KROZ II -- UPDATED VOLUME TWO OF THE KROZ SERIES')
        console.writeln()
        console.gotoxy(24, console.cursor_y)
        Col(14, 7, console)
        console.writeln('Copyright (C) 1990 Scott Miller')
        console.writeln()
        console.writeln('           User-Supported Software -- $7.50 Registration Fee Required')
        Col(11, 7, console)
        console.gotoxy(27, 25)
        console.write('Press any key to continue.')
        console.delay(300)
    ClearKeys(console)
    Bak(1, 0, console)
    console.clrscr()
    console.gotoxy(29, 1)
    Col(4, 7, console)
    Bak(1, 0, console)
    console.write('▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄')
    console.gotoxy(29, 3)
    console.write('▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄')
    console.gotoxy(25, 5)
    Col(15, 15, console)
    console.write('An Apogee Software Production')
    console.gotoxy(28, 7)
    console.write('Created by Scott Miller')
    console.gotoxy(1, 9)
    Col(11, 7, console)
    console.writeln('  Dungeons of Kroz is a game of adventure, exploration and survival.  You are')
    console.writeln('  an intrepid archaeologist in search of the Magical Staff,  hidden somewhere')
    console.writeln('  deep in the vast and dangerous underground dungeons. You enter the dungeons')
    console.writeln('  through a secret tunnel and ignite your brass lantern. Your only protection')
    console.writeln('  is a worn leather whip and your ingenuity.  Sweat beading on your forehead,')
    console.writeln('                you embark on a journey that may be your last...')
    console.gotoxy(1, 17)
    Col(10, 7, console)
    console.write('         Use the cursor keys to mvoe yourself (')
    Col(14, 15, console)
    console.write(2)
    Col(10, 7, console)
    console.writeln(') through the dungeons.')
    console.writeln('            Use your whip (press W) to destroy all nearby creatures.')
    console.writeln('       You are on your own to discover what other mysteries await--some')
    console.writeln('                           helpful, others deadly...')
    Col(14, 7, console)
    console.gotoxy(13, 22)
    console.write('Are you a ')
    Col(15, 15, console)
    console.write('N')
    Col(14, 7, console)
    console.write('ovice, an ')
    Col(15, 15, console)
    console.write('E')
    Col(14, 7, console)
    console.write('xperienced or an ')
    Col(15, 15, console)
    console.write('A')
    Col(14, 7, console)
    console.write('dvanced player?')
    Col(28, 16)
    console.write(219)
    console.sound(220, 100)
    Bak(4, 7, console)
    ch = 0
    selections = set([pygame.locals.K_n, pygame.locals.K_SPACE, pygame.locals.K_e, pygame.locals.K_a, pygame.locals.K_x, pygame.locals.K_RETURN, pygame.locals.K_KP_ENTER])
    while ch not in selections:
        while not console.keypressed():
            console.gotoxy(29, 2)
            Col(randint(16), 0, console)
            console.write(' DUNGEONS OF KROZ II ')
            console.delay(50)
        ch = console.read()
        console.sound(300, 100)
        Bak(4, 7, console)
    console.sound(700, 100)
    console.gotoxy(13, 22)
    Col(0, 0, console)
    Bak(1, 0, console)
    if ch in [pygame.locals.K_n, pygame.locals.K_SPACE, pygame.locals.K_KP_ENTER, pygame.locals.K_RETURN]:
        game.Difficulty = 8
        console.gotoxy(37, 22)
        console.write('NOVICE')
    elif ch == pygame.locals.K_e:
        game.Difficulty = 5
        console.gotoxy(34, 22)
        console.write('EXPERIENCED')
    elif ch == pygame.locals.K_a:
        game.Difficulty = 2
        console.gotoxy(36, 22)
        console.write('ADVANCED')
    elif ch == pygame.locals.K_x:
        game.Difficulty = 9
        console.gotoxy(34, 22)
        console.write('SECRET MODE')
    ClearKeys(console)
    console.gotoxy(33, 25)
    Col(7, 7, console)
    console.write('Press any key.')
    Bak(4, 7, console)
    while not console.keypressed():
        console.gotoxy(29, 2)
        Col(randint(16), 0, console)
        console.write(' DUNGEONS OF KROZ II ')
        console.delay(50)
    ClearKeys(console)

    Shareware(console, Wait = True)

    start_game = False
    while not start_game:
        Bak(0, 0, console)
        console.clrscr()
        Col(15, 9, console)
        console.gotoxy(31, 2)
        console.write('DUNGEONS OF KROZ II')
        console.gotoxy(17, 4)
        Col(6, 7, console)
        console.write('Copyright (c) 1990 Apogee Software Productions')
        console.gotoxy(25, 6)
        console.write('Version 2.0 -- by Scott Miller')
        console.gotoxy(4, 8)
        Col(2, 7, console)
        console.writeln('THIS GAME MAY NOT BE DISTRIBUTED BY SHAREWARE OR PUBLIC DOMAIN LIBRARIES,')
        console.gotoxy(5, 9)
        console.writeln('OR BULLETIN BOARD SYSTEMS.  ONLY KINGDOM OF KROZ II MAY BE DISTRIBUTED.')
        console.gotoxy(1, 10)
        Col(4, 7, console)
        for _ in range(80):
            console.write(196)
        Col(14, 15, console)
        console.gotoxy(28, 12)
        console.write('B')
        Col(11, 7, console)
        console.write('egin your descent into Kroz...')
        Col(14, 15, console)
        console.gotoxy(28, 14)
        console.write('I')
        Col(11, 7, console)
        console.write('nstructions')
        Col(14, 15, console)
        console.gotoxy(28, 16)
        console.write('M')
        Col(11, 7, console)
        console.write('arketing Kroz')
        Col(14, 15, console)
        console.gotoxy(28, 18)
        console.write('S')
        Col(11, 7, console)
        console.write('tory Behind Kroz')
        Col(14, 15, console)
        console.gotoxy(28, 20)
        console.write('O')
        Col(11, 7, console)
        console.write('riginal Kroz Games')
        Col(14, 15, console)
        console.gotoxy(28, 22)
        console.write('A')
        Col(11, 7, console)
        console.write('bout the Author')
        console.gotoxy(26, 24)
        Col(15, 0, console)
        Bak(1, 7, console)
        console.write('Your choice (B/I/M/S/O/A)? B')
        console.gotoxy(console.cursor_x - 1, console.cursor_y)
        ClearKeys(console)
        ch = console.read()
        ClearKeys(console)
        if ch == pygame.locals.K_r:
            game.MixUp = True
        elif ch == pygame.locals.K_b:
            for x in range(100, 20, -1):
                for y in range(10, 1, -1):
                    console.sound(x * y * y, y / 2)
            start_game = True
        elif ch == pygame.locals.K_i:
            Bak(1, 0, console)
            console.clrscr()
            ClearKeys(console)
            console.gotoxy(32, 2)
            Col(14, 7, console)
            console.writeln('THE INSTRUCTIONS')
            console.gotoxy(32, 3)
            console.writeln('────────────────')
            console.writeln()
            Col(15, 7, console)
            console.writeln('   Dungeons of Kroz is a game of exploration and survival. Your journey will')
            console.writeln(' take you through 30 very dangerous chambers, each riddled with diabolical')
            console.writeln(' traps and hideous creatures.   Hidden in the deepest chamber lies a hidden')
            console.writeln(' treasure of immense value.  Use the cursor pad to move 8 directions.')
            console.writeln('   The chambers contain dozens of treasures, spells, traps and other unknowns.')
            console.writeln(' Touching an object for the first time will reveal a little of its identity,')
            console.writeln(' but it will be left to you to decide how best to use it--or avoid it.')
            console.writeln('   When a creature touches you it will vanish, taking with it a few of your')
            console.writeln(' gems that you have collected. If you have no gems then the creature will')
            console.writeln(' instead take your life!  Whips can be used to kill nearby creatures, but')
            console.writeln(' they''re better used to smash through "breakable walls" and other terrain.')
            console.writeln('   Laptop and PCjr players can')
            console.writeln(' use the alternate cursor             U I O      ( NW N NE )')
            console.writeln(' pad instead of the cursor             J K       (   W E   )')
            console.writeln(' keys to move your man, plus          N M ,      ( SW S SE )')
            console.writeln(' the four normal cursor keys.')
            console.writeln('   It''s a good idea to save your game at every new level, therefore, if you die')
            console.writeln(' you can easily restore the game at that level and try again.')
            console.writeln('   Registered users will get a "secret code" that makes this game much easier!')
            Flash(27, 25, 'Press any key to continue.', console)
            Bak(1, 0, console)
            console.clrscr()
            ClearKeys(console)
            console.gotoxy(32, 2)
            Col(14, 7, console)
            console.writeln('THE INSTRUCTIONS')
            console.gotoxy(32, 3)
            console.writeln('────────────────')
            console.writeln()
            Col(15, 7, console)
            console.writeln('   Dungeons of Kroz will present you with many challenges.  You will venture')
            console.writeln(' deep underground and probably not make it out alive!')
            console.writeln()
            console.writeln(' Hints:  ■ Don''t forget to use the Home, End, PgUp, and PgDn keys to move your')
            console.writeln('           on-screen character diagonally (along with the marked cursor keys).')
            console.writeln()
            console.writeln('         ■ Use your player to touch each new object to find out about it.  When')
            console.writeln('           you first touch an object a message appears at the bottom of the')
            console.writeln('           screen that describes it.')
            console.writeln()
            console.writeln('         ■ Collect keys to unlock doors, which usually block the stairs.')
            console.writeln()
            console.writeln('         ■ The faster monsters are the most dangerous to touch--they will knock')
            console.writeln('           off three of your valuable gems.  The slowest creatures only take a')
            console.writeln('           single gem from you, and the medium speed monsters take two.')
            console.writeln()
            Flash(27, 25, 'Press any key to continue.', console)