from colors import Colors
from random import randrange

import pygame.locals

from crt import Crt
from levels import Game, Level, Shareware, VisibleTiles, YTOP
import sounds

def Title(game: Game, level: Level, console: Crt):
    console.clearkeys()
    console.reset_colors()
    console.clrscr()
    console.gotoxy(28, 2)
    console.writeln('Apogee Software Presents')
    console.clearkeys()
    while not console.keypressed():
        console.gotoxy(1, 5)
        console.default_colors(Colors.Code[Colors.Random()])
        console.writeln('     ███     ███     ██████████         ███████████        █████████████  (R)')
        console.writeln('     ███▒▒  ███▒▒▒   ███▒▒▒▒▒███▒      ███▒▒▒▒▒▒▒███▒        ▒▒▒▒▒▒████▒▒▒')
        console.writeln('     ███▒▒ ███▒▒▒    ███▒▒   ███▒▒     ███▒▒     ███▒▒            ███▒▒▒▒')
        console.writeln('     ███▒▒███▒▒▒     ███▒▒   ███▒▒    ███▒▒▒      ███▒           ███▒▒▒')
        console.writeln('     ███▒███▒▒▒      ██████████▒▒▒    ███▒▒       ███▒▒         ███▒▒▒')
        console.writeln('     ██████▒▒▒       ███▒▒███▒▒▒▒     ███▒▒       ███▒▒        ███▒▒▒')
        console.writeln('     ███▒███▒        ███▒▒ ███▒        ███▒      ███▒▒▒       ███▒▒▒')
        console.writeln('     ███▒▒███▒       ███▒▒  ███▒       ███▒▒     ███▒▒      ████▒▒▒')
        console.writeln('     ███▒▒ ███▒      ███▒▒   ███▒       ███████████▒▒▒     █████████████')
        console.writeln('     ███▒▒  ███▒       ▒▒▒     ▒▒▒        ▒▒▒▒▒▒▒▒▒▒▒        ▒▒▒▒▒▒▒▒▒▒▒▒▒')
        console.writeln('     ███▒▒   ███▒')
        console.writeln('     ███▒▒    ███████████████████████████████████████████████████████████')
        console.writeln('       ▒▒▒      ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒')
        console.writeln()
        console.gotoxy(11, console.cursor_y)
        console.writeln('DUNGEONS OF KROZ II -- UPDATED VOLUME TWO OF THE KROZ SERIES', Colors.Yellow)
        console.writeln()
        console.gotoxy(24, console.cursor_y)
        console.writeln('Copyright (C) 1990 Scott Miller', Colors.Yellow)
        console.writeln()
        console.writeln('           User-Supported Software -- $7.50 Registration Fee Required', Colors.Yellow)
        console.gotoxy(27, 25)
        console.write('Press any key to continue.', Colors.LightCyan, Colors.LightGrey)
        console.delay(300)
    console.clearkeys()
    console.default_colors(Colors.Red, Colors.Blue)
    console.clrscr(Colors.Blue)
    console.gotoxy(29, 1)
    console.write('▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄')
    console.gotoxy(29, 3)
    console.write('▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄')
    console.gotoxy(25, 5)
    console.write('An Apogee Software Production', Colors.LightCyan)
    console.gotoxy(28, 7)
    console.write('Created by Scott Miller', Colors.LightCyan)
    console.gotoxy(1, 9)
    console.default_colors(Colors.LightCyan)
    console.writeln('  Dungeons of Kroz is a game of adventure, exploration and survival.  You are')
    console.writeln('  an intrepid archaeologist in search of the Magical Staff,  hidden somewhere')
    console.writeln('  deep in the vast and dangerous underground dungeons. You enter the dungeons')
    console.writeln('  through a secret tunnel and ignite your brass lantern. Your only protection')
    console.writeln('  is a worn leather whip and your ingenuity.  Sweat beading on your forehead,')
    console.writeln('                you embark on a journey that may be your last...')
    console.gotoxy(1, 17)
    console.write('         Use the cursor keys to move yourself (', Colors.LightGreen)
    console.write(VisibleTiles.Player, Colors.Yellow)
    console.writeln(') through the dungeons.')
    console.writeln('            Use your whip (press W) to destroy all nearby creatures.')
    console.writeln('       You are on your own to discover what other mysteries await--some')
    console.writeln('                           helpful, others deadly...')
    console.default_colors(Colors.Yellow)
    console.gotoxy(13, 22)
    console.write('Are you a ')
    console.write('N', Colors.White)
    console.write('ovice, an ')
    console.write('E', Colors.White)
    console.write('xperienced or an ')
    console.write('A', Colors.White)
    console.write('dvanced player?')
    console.write(219, Colors.LightRed) # Flashing when possible
    console.sounds(sounds.Difficulty_Prompt())
    console.default_colors(back = Colors.Red)
    ch = 0
    selections = set([pygame.locals.K_n, pygame.locals.K_SPACE, pygame.locals.K_e, pygame.locals.K_a, pygame.locals.K_x, pygame.locals.K_RETURN, pygame.locals.K_KP_ENTER])
    while ch not in selections:
        while not console.keypressed():
            console.gotoxy(29, 2)
            console.write(' DUNGEONS OF KROZ II ', Colors.Code[Colors.Random()])
            console.delay(50)
        ch = console.read()
        console.sounds(sounds.Difficulty_Key())
    console.sounds(sounds.Difficulty_Prompt())
    console.gotoxy(13, 22)
    if ch in [pygame.locals.K_n, pygame.locals.K_SPACE, pygame.locals.K_KP_ENTER, pygame.locals.K_RETURN]:
        game.Difficulty = 8
        console.gotoxy(37, 22)
        console.write('NOVICE', Colors.Black, Colors.Blue)
    elif ch == pygame.locals.K_e:
        game.Difficulty = 5
        console.gotoxy(34, 22)
        console.write('EXPERIENCED', Colors.Black, Colors.Blue)
    elif ch == pygame.locals.K_a:
        game.Difficulty = 2
        console.gotoxy(36, 22)
        console.write('ADVANCED', Colors.Black, Colors.Blue)
    elif ch == pygame.locals.K_x:
        game.Difficulty = 9
        console.gotoxy(34, 22)
        console.write('SECRET MODE', Colors.Black, Colors.Blue)
    console.clearkeys()
    console.gotoxy(33, 25)
    console.write('Press any key.', Colors.LightGrey, Colors.Blue)
    while not console.keypressed():
        console.gotoxy(29, 2)
        console.write(' DUNGEONS OF KROZ II ', Colors.Code[Colors.Random()], Colors.Red)
        console.delay(50)
    console.clearkeys()

    Shareware(console, Wait = True)

    start_game = False
    while not start_game:
        console.reset_colors()
        console.clrscr()
        console.gotoxy(31, 2)
        console.write('DUNGEONS OF KROZ II')
        console.gotoxy(17, 4)
        console.write('Copyright (c) 1990 Apogee Software Productions', Colors.Brown)
        console.gotoxy(25, 6)
        console.write('Version 2.0 -- by Scott Miller', Colors.Brown)
        console.gotoxy(4, 8)
        console.writeln('THIS GAME MAY NOT BE DISTRIBUTED BY SHAREWARE OR PUBLIC DOMAIN LIBRARIES,', Colors.Green)
        console.gotoxy(5, 9)
        console.writeln('OR BULLETIN BOARD SYSTEMS.  ONLY KINGDOM OF KROZ II MAY BE DISTRIBUTED.', Colors.Green)
        console.gotoxy(1, 10)
        for _ in range(80):
            console.write(196, Colors.Red)
        console.default_colors(Colors.LightCyan)
        console.gotoxy(28, 12)
        console.write('B', Colors.Yellow)
        console.write('egin your descent into Kroz...')
        console.gotoxy(28, 14)
        console.write('I', Colors.Yellow)
        console.write('nstructions')
        console.gotoxy(28, 16)
        console.write('M', Colors.Yellow)
        console.write('arketing Kroz')
        console.gotoxy(28, 18)
        console.write('S', Colors.Yellow)
        console.write('tory Behind Kroz')
        console.gotoxy(28, 20)
        console.write('O', Colors.Yellow)
        console.write('riginal Kroz Games')
        console.gotoxy(28, 22)
        console.write('A', Colors.Yellow)
        console.write('bout the Author')
        console.gotoxy(26, 24)
        console.default_colors(Colors.White, Colors.Blue)
        console.write('Your choice (B/I/M/S/O/A)? B')
        console.gotoxy(console.cursor_x - 1, console.cursor_y)
        console.clearkeys()
        ch = console.read()
        console.clearkeys()
        if ch == pygame.locals.K_r:
            game.MixUp = True
        elif ch == pygame.locals.K_b:
            console.sounds(sounds.Begin_Game())
            start_game = True
        elif ch == pygame.locals.K_i:
            console.clrscr()
            console.clearkeys()
            console.gotoxy(32, 2)
            console.writeln('THE INSTRUCTIONS', Colors.Yellow)
            console.gotoxy(32, 3)
            console.writeln('────────────────', Colors.Yellow)
            console.writeln()
            console.writeln('   Dungeons of Kroz is a game of exploration and survival. Your journey will')
            console.writeln(' take you through 30 very dangerous chambers, each riddled with diabolical')
            console.writeln(' traps and hideous creatures.   Hidden in the deepest chamber lies a hidden')
            console.writeln(' treasure of immense value.  Use the cursor pad to move 8 directions.')
            console.writeln('   The chambers contain dozens of treasures, spells, traps and other unknowns.')
            console.writeln(' Touching an object for the first time will reveal a little of its identity,')
            console.writeln(' but it will be left to you to decide how best to use it--or avoid it.')
            console.writeln('   When a creature touches you it will vanish, taking with it a few of your')
            console.writeln(' gems that you have collected. If you have no gems then the creature will')
            console.writeln(' instead take your life!  Whips can be used to kill nearby creatures, but')
            console.writeln(' they''re better used to smash through "breakable walls" and other terrain.')
            console.writeln('   Laptop and PCjr players can')
            console.writeln(' use the alternate cursor             U I O      ( NW N NE )')
            console.writeln(' pad instead of the cursor             J K       (   W E   )')
            console.writeln(' keys to move your man, plus          N M ,      ( SW S SE )')
            console.writeln(' the four normal cursor keys.')
            console.writeln('   It''s a good idea to save your game at every new level, therefore, if you die')
            console.writeln(' you can easily restore the game at that level and try again.')
            console.writeln('   Registered users will get a "secret code" that makes this game much easier!')
            console.alert(YTOP + 1, 'Press any key to continue', Colors.Code[level.Bc], Colors.Code[level.Bb])
            console.clrscr()
            console.clearkeys()
            console.gotoxy(32, 2)
            console.writeln('THE INSTRUCTIONS', Colors.Yellow)
            console.gotoxy(32, 3)
            console.writeln('────────────────', Colors.Yellow)
            console.writeln()
            console.writeln('   Dungeons of Kroz will present you with many challenges.  You will venture')
            console.writeln(' deep underground and probably not make it out alive!')
            console.writeln()
            console.writeln(' Hints:  ■ Don''t forget to use the Home, End, PgUp, and PgDn keys to move your')
            console.writeln('           on-screen character diagonally (along with the marked cursor keys).')
            console.writeln()
            console.writeln('         ■ Use your player to touch each new object to find out about it.  When')
            console.writeln('           you first touch an object a message appears at the bottom of the')
            console.writeln('           screen that describes it.')
            console.writeln()
            console.writeln('         ■ Collect keys to unlock doors, which usually block the stairs.')
            console.writeln()
            console.writeln('         ■ The faster monsters are the most dangerous to touch--they will knock')
            console.writeln('           off three of your valuable gems.  The slowest creatures only take a')
            console.writeln('           single gem from you, and the medium speed monsters take two.')
            console.writeln()
            console.alert(YTOP + 1, 'Press any key to continue.', Colors.Code[level.Bc], Colors.Code[level.Bb])
            console.clrscr()
            console.clearkeys()
            console.gotoxy(32, 2)
            console.writeln('THE INSTRUCTIONS', Colors.Yellow)
            console.gotoxy(32, 3)
            console.writeln('────────────────', Colors.Yellow)
            console.writeln('   Here are some brief descriptions of the most common objects that you are')
            console.writeln(' likely to find in the Dungeons of Kroz:')
            console.writeln()
            console.write('      ')
            console.write(VisibleTiles.Player, Colors.Yellow)
            console.writeln(' - this is you, a dauntless archaeologist without peer')
            console.write('      ')
            console.write(VisibleTiles.SMonster_1, Colors.LightRed)
            console.writeln(' - red creatures move slow and only knock off 1 gem when touched')
            console.write('      ')
            console.write(VisibleTiles.MMonster_1, Colors.LightGreen)
            console.writeln(' - green creatures move faster and knock off 2 gems when touched')
            console.write('      ')
            console.write(VisibleTiles.FMonster_1, Colors.LightBlue)
            console.writeln(' - blue creatures move fastest and knock off 3 gems when touched')
            console.write('      ')
            console.write(VisibleTiles.Gem, Colors.Code[randrange(13) + 2])
            console.writeln(' - collect all the gems you can to survive creature attacks')
            console.write('      ')
            console.write(VisibleTiles.Whip)
            console.writeln(' - whips are used to wipe out creatures and smash certain walls')
            console.write('      ')
            console.write(VisibleTiles.Teleport, Colors.LightMagenta)
            console.writeln(' - teleport spells will magically transport you to a random place')
            console.write('      ')
            console.write(VisibleTiles.Chest, Colors.Yellow, Colors.Red)
            console.writeln(' - chests contain a random number of gems and whips')
            console.write('      ')
            console.write(VisibleTiles.Key, Colors.LightRed)
            console.write(' - collect keys to go through doors (')
            console.write(VisibleTiles.Door, Colors.Cyan, Colors.Magenta)
            console.writeln(')')
            console.write('      ')
            console.write(VisibleTiles.Power)
            console.writeln(' - collect these power rings to make your whips more powerful')
            console.write('      ')
            console.write(VisibleTiles.Stairs, Colors.Black, Colors.LightGrey) # Flashing when possible
            console.writeln(' - stairs take you to the next level deeper in Kroz')
            console.writeln()
            console.writeln('   There are dozens and dozens of other objects to discover.  The best way')
            console.writeln(' to learn the usefulness of any new object is to touch it and read the brief')
            console.writeln(' message that appears at the bottom of the screen.')
            console.alert(YTOP + 1, 'Press any key to continue.', Colors.Code[level.Bc], Colors.Code[level.Bb])
            console.clrscr()
            console.clearkeys()
            console.gotoxy(33, 2)
            console.writeln('MISCELLANEOUS', Colors.Yellow)
            console.gotoxy(33, 3)
            console.writeln('─────────────', Colors.Yellow)
            console.writeln()
            console.writeln()
            console.writeln('  ■ You can now save three different levels during a single game.  When you')
            console.writeln('    select the "save" command you will also be asked to enter a letter, either')
            console.writeln('    A, B or C.  If you just hit the space bar then A is the default selection.')
            console.writeln('    These letters do not refer to disk drives!  They actually refer to the file')
            console.writeln('    names used by the game.  The restore command lets use pick from A, B or C.')
            console.writeln()
            console.writeln('  ■ If you are tired of seeing the descriptions at the bottom of the screen')
            console.writeln('    that appear whenever you touch a new object, you can disable most of the')
            console.writeln('    messages by pressing the minus (-) key.  The plus key (+) resets messages.')
            console.alert(YTOP + 1, 'Press any key to continue.', Colors.Code[level.Bc], Colors.Code[level.Bb])
        elif ch == pygame.locals.K_m:
            console.clrscr()
            console.clearkeys()
            console.gotoxy(29, 2)
            console.writeln('THE MARKETING OF KROZ', Colors.Yellow)
            console.gotoxy(29, 3)
            console.writeln('─────────────────────', Colors.Yellow)
            console.writeln()
            console.writeln()
            console.writeln('   Dungeons of Kroz II is a user-supported game. This means that the creator of')
            console.writeln(' this program relies on the appreciation of honest players to pay the game''s')
            console.writeln(' registration fee--$7.50.')
            console.writeln('   Payment of this fee entitles you to all the free help and hints you might')
            console.writeln(' need to enjoy the game.  All letters from registered users are answered')
            console.writeln(' within two days.  (Try to get this kind of support from commercial games!)')
            console.writeln('   Also, players can order the other Kroz sequels ONLY if this registration')
            console.writeln(' fee is paid.  ($7.50 each or $20 for The Lost Adventures of Kroz.)')
            console.writeln('   Everyone who orders (or registers) any of the other six Kroz games will also')
            console.writeln(' get a "Hints, Tricks and Scoring Secrets" guide, and "The Domain of Kroz" map.')
            console.writeln('   A single Kroz game takes several months to create, up to 200 hours per game!')
            console.writeln(' I can''t afford to devote this much time without receiving something in return.')
            console.writeln(' That is why I ask for this small fee, which is only necessary if you enjoy')
            console.writeln(' this game.  In other words, try before you buy.')
            console.writeln('   Even if you buy this game from a public domain or shareware library, I don''t')
            console.writeln(' receive any of that money.  You''re simply paying for "storage, distribution,')
            console.writeln(' disk, and handling."')
            console.writeln('   Note:  The current Apogee Software address will ALWAYS BE VALID.  Foreign')
            console.writeln(' orders are always welcome, please send U.S. funds/money orders only.')
            console.alert(YTOP + 1, 'Press any key to continue.', Colors.Code[level.Bc], Colors.Code[level.Bb])
        elif ch == pygame.locals.K_s:
            console.clrscr()
            console.clearkeys()
            console.gotoxy(29, 2)
            console.writeln('THE STORY BEHIND KROZ', Colors.Yellow)
            console.gotoxy(29, 3)
            console.writeln('─────────────────────', Colors.Yellow)
            console.writeln()
            console.writeln('   The original Kroz Trilogy (consisting of Caverns of Kroz, Dungeons of Kroz,')
            console.writeln(' and Kingdom of Kroz) was developed after I spent many hours playing another')
            console.writeln(' explore-the-levels type game titled Rogue.  I never could finish Rogue,')
            console.writeln(' though, because the game relied too much on luck and random occurrences.')
            console.writeln('   The name "Kroz" is actually Zork (an Infocom text adventure) spelled in')
            console.writeln(' reverse.  Many players still inquire about this bit of trivia.  The game was')
            console.writeln(' first designed without predefined level layouts, meaning every level was a')
            console.writeln(' random placement of creatures and play field objects.  New objects, like')
            console.writeln(' spells, lava, doors, etc., were added quickly as the first Kroz game took')
            console.writeln(' shape, including the ability to have predefined level floor plans.')
            console.writeln('   My main objective was to create a game that wasn''t all fast paced action,')
            console.writeln(' but also included strategy and puzzle solving.  Kingdom of Kroz was entered')
            console.writeln(' in a national programming contest in 1988 and took top honors in the game')
            console.writeln(' category, and number two overall (beaten by a spreadsheet program.)')
            console.writeln('   The latest Kroz games have been greatly re-designed and re-programmed, but')
            console.writeln(' the familiar appearance has been mostly maintained.  You will discover new')
            console.writeln(' dangers, creatures and objects in your adventures below.')
            console.writeln('   Thanks to all the players of Kroz who contributed dozens of suggestions,')
            console.writeln(' ideas and improvements that were incorporated in later versions of Kroz.')
            console.alert(YTOP + 1, 'Press any key to continue.', Colors.Code[level.Bc], Colors.Code[level.Bb])
            console.clrscr()
            console.clearkeys()
            console.gotoxy(29, 2)
            console.writeln('THE STORY BEHIND KROZ', Colors.Yellow)
            console.gotoxy(29, 3)
            console.writeln('─────────────────────', Colors.Yellow)
            console.writeln()
            console.writeln('   Kroz is a hobby that''s gotten out of control!')
            console.writeln('   Kroz is truly a phenomenon in the user-supported software market.  The')
            console.writeln(' overwhelming success of the original Kroz games was completely unexpected.')
            console.writeln(' Most (probably 99%) of all "shareware" games are not profitable for their')
            console.writeln(' creator.  This is a well-known fact among the community of shareware game')
            console.writeln(' authors, and one that I''ve verified by speaking to many other games de-')
            console.writeln(' signers.  Most people simply don''t register games.')
            console.writeln('   Through my research the Kroz games are the only user-supported games that')
            console.writeln(' generate a substantial amount of registrations and orders for it''s creator,')
            console.writeln(' namely, Scott Miller (me).  I don''t know what cord I''ve struck with players,')
            console.writeln(' but everyday I receive fascinating and appreciative letters from players')
            console.writeln(' telling me how much they enjoy the Kroz games.')
            console.writeln('   Thanks to Kroz I now know what a mutual fund is, but on the downside my')
            console.writeln(' taxes require a book two inches thick to figure out.')
            console.writeln('   Will Kroz ever end?  I thought that THE FINAL CRUSADE would be the closing')
            console.writeln(' chapter--but a flood of letters demanding more proved that I''m a pushover.')
            console.writeln(' I guess as long as the letters keep coming, I''ll continue to make Kroz games.')
            console.writeln(' After all, Kroz is like my second home now, one that I like to visit often...')
            console.writeln('                                                        -- Scott Miller')
            console.alert(YTOP + 1, 'Press any key to continue.', Colors.Code[level.Bc], Colors.Code[level.Bb])
        elif ch == pygame.locals.K_o:
            console.clrscr()
            console.clearkeys()
            console.gotoxy(28, 2)
            console.writeln('THE ORIGINAL KROZ GAMES', Colors.Yellow)
            console.gotoxy(28, 3)
            console.writeln('───────────────────────', Colors.Yellow)
            console.writeln()
            console.writeln('   The Lost Adventures of Kroz is the latest addition to the Kroz family of')
            console.writeln(' games.  Before this game there are six more Kroz volumes, separated into two')
            console.writeln(' triligies:  The Kroz Trilogy and The Super Kroz Trilogy.')
            console.writeln('   The original Kroz Trilogy was such a surprising success that I decided to')
            console.writeln(' created a second "Super Kroz" trilogy.  The first three original Kroz')
            console.writeln(' games are:   ■ Kingdom of Kroz  ■ Caverns of Kroz  ■ Dungeons of Kroz.')
            console.writeln(' All three are still available and are constantly being updated and improved.')
            console.writeln('   The original Kroz Trilogy games can be purchased for $7.50 each, or all 3')
            console.writeln(' for $20 (these prices include postage, disks, and handling).')
            console.writeln('   Only Kingdom of Kroz can be placed in a shareware library for distribution,')
            console.writeln(' and the other two can only be ordered from Apogee Software Productions.')
            console.writeln('   The Super Kroz Trilogy volumes are revamped and greatly improved.  They are')
            console.writeln(' ■ Return to Kroz  ■ Temple of Kroz  ■ The Final Crusade of Kroz.  The last')
            console.writeln(' three volumes were supposed to be the end of Kroz, but the mail kept coming')
            console.writeln(' and again I was impelled to create another Kroz adventure.')
            console.writeln('   All Kroz games work on all monitors, either graphics or monochrome systems.')
            console.writeln(' Plus, they only rely on keyboard control, and have slow-down routines that')
            console.writeln(' permit them to function correctly on any speed IBM PC compatible computer.')
            console.alert(YTOP + 1, 'Press any key to continue.', Colors.Code[level.Bc], Colors.Code[level.Bb])
        elif ch == pygame.locals.K_a:
            console.clrscr()
            console.clearkeys()
            console.gotoxy(32, 2)
            console.writeln('ABOUT THE AUTHOR', Colors.Yellow)
            console.gotoxy(32, 3)
            console.writeln('────────────────', Colors.Yellow)
            console.writeln('   Scott Miller, the creator of all the Kroz games, along with Supernova, Trek')
            console.writeln(' Trivia and Beyond the Titanic (all shareware games) began programming in high')
            console.writeln(' school in 1975.  Since then he''s created over 100 games and has had dozens')
            console.writeln(' publishered by BIG BLUE DISK, I.B.Magazette and Keypunch Software.')
            console.writeln()
            console.writeln('   For over three years he wrote two weekly computer columns for the Dallas')
            console.writeln(' Morning News, one of the nation''s largest newspapers.  He also co-authored')
            console.writeln(' a video game strategy book titled, "Shootout: Beating the Video Games."')
            console.writeln(' Scott has written articles for COMPUTE!''s PC and PCjr Magazine and is a')
            console.writeln(' software reviewer with COMPUTE! Publications.');        
            console.writeln()
            console.writeln('   Hobbies include softball, running, tennis, karate (1st degree black belt),')
            console.writeln(' drumming, rock music, science fiction, and creating new computer games.')
            console.writeln(' Favorite computer games are M.U.L.E., Jumpman, Planetfall, Enchanter, Zork,')
            console.writeln(' Spelunker, and Archon.  All are games of strategy, with action secondary.')
            console.writeln()
            console.writeln('   Scott creates all Apogee Software programs on an AST Premium 80386 (20 Mhz)')
            console.writeln(' equipped with VGA graphics, a NEC MultiSync II and an HP LaserJet series III.')
            console.writeln(' The cost to market each Kroz game to the many shareware libraries and BBS''s')
            console.writeln(' is over $10,000 per game.  All of the appreciative letters make it worth it!')
            console.alert(YTOP + 1, 'Press any key to continue.', Colors.Code[level.Bc], Colors.Code[level.Bb])
        else:
            console.sounds(sounds.Begin_Game())
            start_game = True
    console.reset_colors()
    console.clrscr()